eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/shopping_db
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        # noinspection undefined
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: false
